# Generated by Django 5.2.7 on 2025-10-23 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('front', models.CharField(help_text="Card's front side")),
                ('back', models.CharField(help_text="Card's back side")),
                ('due', models.DateTimeField(default=datetime.datetime(2025, 10, 23, 17, 20, 39, 356998), null=True)),
            ],
        ),
    ]
