# Generated by Django 5.2.7 on 2025-10-23 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='The topic you want to learn')),
                ('context', models.CharField(help_text='What you already know about the subject')),
                ('goal', models.CharField(help_text='What you want to accomplish after learning the topic')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 23, 18, 42, 0, 866365), null=True),
        ),
    ]
