# Generated by Django 5.2.7 on 2025-10-23 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_preferences_alter_card_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user_retention',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 23, 23, 6, 49, 385194), null=True),
        ),
    ]
