# Generated by Django 5.2.7 on 2025-10-23 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_card_user_retention_alter_card_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user_retention',
            new_name='user_review',
        ),
        migrations.AlterField(
            model_name='card',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 24, 2, 16, 23, 502569), null=True),
        ),
    ]
